// Slicer code credit to Nesvi, thanks!
// https://answers.unity.com/questions/840983/how-do-i-copy-a-3d-rendertexture-isvolume-true-to.html?childToView=1243556#answer-1243556

#pragma kernel CSMain

Texture3D<float4> voxels;
RWTexture2D<float4> Result;
int layer;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	uint3 pos = uint3(id.x, id.y, layer);
	Result[id.xy] = voxels[pos];
}
